### ISSUE TITLE
Visualize DOLs

### ISSUE THREAD

**Issue by RictusSaveus** [kaphacius/just-tags#19]
Data Objects List such as PDOLs are hard to read in the current visualisation. The visualisation of DOLs should be straightforward since the individual elements in the DOLs are just sequences of TLs(TagLengths). The utility should therefore do 2 steps in the decoding process:
i) Identify that the parsed TLV is a DOL. For eg., 9F38 is the Processing Options Data Object List used in the GPO command.
ii) Actually deserialise the value of this TLV to visualise it as a sequence of TLs.

**Comment by kaphacius** [comment]
@RictusSaveus thank you for opening an issue. what do you think would be the best way to identify that the tag is actually a DOL? just hardcoding the known DOL tags? looking at tag name?

**Comment by RictusSaveus** [comment]
Since there is nothing in that identifies a tag as DOL tag, hardcoding the known DOL tags is the only way unfortunately.
Some DOLs I found in the C-2 spec are:
- PDOL - 9F38
- CDOL1 - 8C
- DRDOL - 9F51
