### ISSUE TITLE
Zero padded bytes between TLV encoded objects should either be ignored or explicitly indicated!

### ISSUE THREAD

**Issue by RictusSaveus** [kaphacius/just-tags#20]
<img width="573" alt="Screenshot 2023-07-14 at 14 03 03" src="https://github.com/kaphacius/just-tags/assets/40272478/a938900a-124e-4bbd-ac3c-3bc3d81d9f3f">
It's not clear how the 0 padded bytes are being interpreted by the utility and it's also not clear how the user should interpret the 00s in the UI.
Propose to either ignore the padding bytes or explicitly indicate that they are padding bytes.
Right now, they show up like this:

![Screenshot 2023-07-14 at 14 10 09](https://github.com/kaphacius/just-tags/assets/40272478/4e9988ee-c41b-49f1-abb9-93fbdeec92ed)

**Comment by kaphacius** [comment]
@RictusSaveus thank you for opening an issue.
what do you think about this:
<img width="999" alt="Screenshot 2023-07-20 at 14 55 38" src="https://github.com/kaphacius/just-tags/assets/5669951/df713cac-4b38-46e0-a83b-890b02b153dd">
<img width="957" alt="Screenshot 2023-07-20 at 14 56 30" src="https://github.com/kaphacius/just-tags/assets/5669951/c1241242-63a2-404a-be3e-3c5a2984774f">

**Comment by RictusSaveus** [comment]
Yup, this looks good!
