### ISSUE TITLE
Better UI Identification for Embedded Tags

### ISSUE THREAD

**Issue by mcguire-james** [kaphacius/just-tags#3]
Would be nice to have better UI/colour distinction for embedded tags to visually show the structure more.

**Comment by kaphacius** [comment]
Hi @mcguire-james ,
 
Thank you for opening an issue. Do you have an ideas on this? What kind of UI identification would be useful for you?

**Comment by mcguire-james** [comment]
> Hi @mcguire-james ,
> 
> Thank you for opening an issue. Do you have an ideas on this? What kind of UI identification would be useful for you?

I think a better visual separation of the nesting via the use of more contrasting colors.

**Comment by kaphacius** [comment]
@spidey what do you think about this? i don't want to make the border color/thickness too prominent, as the application in general has very muted and calm colors. open to any suggestions.
<img width="998" alt="Screenshot 2023-04-23 at 11 41 17" src="https://user-images.githubusercontent.com/5669951/233832086-cabdd6a6-d609-4573-9d21-2a73d6b44caf.png">

**Comment by spidey** [comment]
Yeah, the suggestion is good. Sorry for reacting so late.
