### ISSUE TITLE
Strip whitespace and newline when parsing clipboard

### ISSUE THREAD

**Issue by kaphacius** [kaphacius/just-tags#37]
Sometimes the text pasted contains a `\n` or a whitespace at the end and it produces an error when pasting.

**Comment by urvi-k** [comment]
@kaphacius Can I work on this issue?

**Comment by kaphacius** [comment]
@urvi-k yes, of course!
thanks for helping out

**Comment by urvi-k** [comment]
@kaphacius Could you please mark it at assigned to me?

**Comment by kaphacius** [comment]
hey @urvi-k , any updates on this? i want to release a new version soon, and it would be a nice addition to it

**Comment by urvi-k** [comment]
hi @kaphacius i am getting following error while running the app.
<img width="575" alt="Screenshot 2024-02-19 at 1 04 48 PM" src="https://github.com/kaphacius/just-tags/assets/50900652/887e3e18-80a9-4f57-abfc-c260bd5e5675">

**Comment by kaphacius** [comment]
> hi @kaphacius i am getting following error while running the app.
> 
> <img width="575" alt="Screenshot 2024-02-19 at 1 04 48 PM" src="https://github.com/kaphacius/just-tags/assets/50900652/887e3e18-80a9-4f57-abfc-c260bd5e5675">
> 
> 

Hey @urvi-k , which version of Xcode are you using? It should work with 15.2.

**Comment by urvi-k** [comment]
Hi @kaphacius, I update my system and xcode, now it works thanks. I am looking at the issue.

**Comment by urvi-k** [comment]
Hi @kaphacius How can i add tags into it? i am seeing following screen and try to add hexadecimal strings as per the article (https://medium.com/@lovisgod/understanding-emv-introduction-to-tlv-40d66bd004e7). "5F20", and i am getting the same error every-time.
<img width="896" alt="Screenshot 2024-02-20 at 1 19 36 AM" src="https://github.com/kaphacius/just-tags/assets/50900652/6308d81b-b4f2-431c-8b93-943c441bb8a6">
 
 Please help me with, how should i test and reproduce the issue.
 Thanks.

**Comment by kaphacius** [comment]
@urvi-k , of course:
as an example to test/reproduce you can use these correct values `9F3303080808` or `nzMDCAgI` (same value but base64 encoded) however, if you add a new line at the end of the first value like below, you would get an error when pasting it (try copying both lines)
```
9F3303080808

```

**Comment by urvi-k** [comment]
@kaphacius Kindly review the PR - https://github.com/kaphacius/just-tags/pull/46
